layout_spectrum: 0.05881881411187351
typography_spectrum: 0.34885789384134114
color:
  brandStrength: 0.7174161253497005
  lightness: 0.9482636817265302
  saturation: 0.2791221507359296
  rhythmicContrast: 0.6821474675089121
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
author:
  name: Kosta Lysenko
  email: lysenko.kostya@gmail.com
name: ipac
navigation:
  - name: 'About '
    id: 1332911c-ea90-459c-8c0e-8aa03bdfcb0e
    type: content
  - name: WDG Public Health
    url: 'https://www.wdgpublichealth.ca/'
    type: external
title: Infection Prevention and Control
description: Healthy Practices leading to Healthy Outcomes
