typography_spectrum: 0.431147834751755
color:
  brandStrength: 0.6268762575928122
  lightness: 0.43275472638197243
  saturation: 0.7364013514015824
  rhythmicContrast: 0.2156213626731187
  brandColors:
    - '#3E454C'
    - '#2185C5'
    - '#7ECEFD'
    - '#FFF6E5'
    - '#FF7F66'
layout_spectrum: 0.8186591679695994
author:
  name: Kosta Lysenko
  email: lysenko.kostya@gmail.com
name: ipac
navigation:
  - name: 'About '
    id: 1332911c-ea90-459c-8c0e-8aa03bdfcb0e
    type: content
  - name: WDG Public Health
    url: 'https://www.wdgpublichealth.ca/'
    type: external
title: Infection Prevention and Control
description: Healthy Practices leading to Healthy Outcomes
