layout_spectrum: 0.7526548709720373
typography_spectrum: 0.1872368163894862
color:
  brandStrength: 0.8799775028601289
  lightness: 0.9893076338339597
  saturation: 0.38579197763465345
  rhythmicContrast: 0.029170332243666053
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
author:
  name: Kosta Lysenko
  email: lysenko.kostya@gmail.com
name: ipac
navigation:
  - name: WDG Public Health
    url: www.wdgpublichealth.ca
    type: external
  - name: Contact Us
    url: 'https://www.wdgpublichealth.ca/?q=contactus'
    type: external
  - name: Health Unit Offices
    url: 'https://www.wdgpublichealth.ca/?q=node/161'
    type: external
title: Infection Prevention and Control
description: Healthy Practices Leading to Healthy Outcomes
