typography_spectrum: 0.19179338170215487
color:
  brandStrength: 0.7174161253497005
  lightness: 0.9482636817265302
  saturation: 0.2791221507359296
  rhythmicContrast: 0.6821474675089121
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.6526385303586721
author:
  name: Kosta Lysenko
  email: lysenko.kostya@gmail.com
name: ipac
navigation:
  - name: WDG Public Health
    url: www.wdgpublichealth.ca
    type: external
  - name: Contact Us
    url: 'https://www.wdgpublichealth.ca/?q=contactus'
    type: external
title: Infection Prevention and Control
description: Healthy Practices Leading to Healthy Outcomes
