layout_spectrum: 0.9909538051579148
typography_spectrum: 0.03738072421401739
color:
  brandStrength: 0.0316324420273304
  lightness: 0.3256856147199869
  saturation: 0.08389957901090384
  rhythmicContrast: 0.6771899377927184
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
author:
  name: Kosta Lysenko
  email: lysenko.kostya@gmail.com
name: ipac
navigation:
  - name: WDG Public Health
    url: www.wdgpublichealth.ca
    type: external
  - name: Contact Us
    url: 'https://www.wdgpublichealth.ca/?q=contactus'
    type: external
  - name: Health Unit Offices
    url: 'https://www.wdgpublichealth.ca/?q=node/161'
    type: external
title: Infection Prevention and Control
description: Healthy Practices Leading to Healthy Outcomes
